### ISSUE TITLE
Does final build also include unminified files of bootstrap as well

### ISSUE THREAD

**Issue by techsin** [highwingers/DesiTv#1]
And do webkit prefixes work on ios

**Comment by highwingers** [comment]
Yes, All files needs to be included within the final build. But those files are relatively small, so it’s not an  issue. Try not to use any CDN, Apple may reject your file if it sees any CDN.

Examine my CSS file, if you see any webkit stuff in there then Yes it supports. My project looked same on both Android & iOS. To see how it looks download app “Desi Tv” to see it in action.

https://play.google.com/store/apps/details?id=com.knowlegezone.desitv https://play.google.com/store/apps/details?id=com.knowlegezone.desitv&hl=en &hl=en

ty
